steps:
  # 1. Build Backend API Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/chat-repo/chat-api:latest'
      - '-f'
      - 'Dockerfile.api'
      - '.'

  # 2. Build Frontend Client Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/chat-repo/chat-client:latest'
      - '-f'
      - 'Dockerfile.client'
      - '.'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/chat-repo/chat-api:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/chat-repo/chat-client:latest'

options:
  logging: CLOUD_LOGGING_ONLY
